{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "install-scripts-controller.configSecretName" . }}
  labels:
    {{- include "install-scripts-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
    site:
      password: "{{ required "secrets.password is required when secrets.create=true" .Values.secrets.password }}"
      install_key_ttl: "{{ .Values.config.installKeyTTL }}"
      public_url: "{{ .Values.config.publicUrl }}"
    server:
      addr: "{{ .Values.config.serverAddr }}"
    database:
      path: "{{ .Values.config.databasePath }}"
{{- end }}
