apiVersion: v1
kind: Secret
metadata:
  name: {{ include "install-scripts-controller.fullname" . }}-config
  labels:
    {{- include "install-scripts-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
    site:
      password: "{{ .Values.config.password }}"
      install_key_ttl: "{{ .Values.config.installKeyTTL }}"
      public_url: "{{ .Values.config.publicUrl }}"
    server:
      addr: "{{ .Values.server.addr }}"
    database:
      path: "{{ .Values.database.path }}"
